name: Quality

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm install

      - name: Run Unit Tests
        run: npm run unit-tests
